Repository getgauge/docs.gauge.org, pull requests merged in 2018-05, with the labels that each got.

#64 Update getting-started.rst
  getting-started.rst
Labels: cla-signed

#62 Update version number
  conf.py
Labels: cla-signed, community

#66 fix in stylesheet for docs landing page and docs details page
  themes/gauge_theme/_landing.html
  themes/gauge_theme/layout.html
  themes/gauge_theme/static/css/theme.css
  themes/gauge_theme/static/js/theme.js
Labels: cla-signed

#65 Update writing-specifications.rst
  writing-specifications.rst
Labels: cla-signed, in progress

#69 Here is not descriptive changed to Github
  reports.rst
Labels: cla-signed

#68 Functionalities sounded funny to Dave and I
  faqs.rst
Labels: cla-signed, in progress

#70 Breadcrumb update
  themes/gauge_theme/_breadcrumbs.html
  themes/gauge_theme/static/css/theme.css
Labels: cla-signed, in progress
