Repository getgauge/docs.gauge.org, pull requests merged in 2019-02, with the labels that each got.

#112 update sphinx to fix document_option.js error
  requirements.txt
  themes/gauge_theme/layout.html
Labels: cla-signed, ready

#114 Adding FAQ for gRPC issues. #111
  faqs.rst
Labels: cla-signed, ready

#116 Updating gauge and plugin versions in install instructions. #115
  installation.rst
Labels: cla-signed, ready for Development

#117 Replaced Contribute section on Docs landing with Taiko
  themes/gauge_theme/_landing.html
Labels: cla-signed, ready, ready for Development
